// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden"
	"medpoinraiden/internal/jobs"
)

func RegisterJobs(server *raiden.Server) {
	server.RegisterJobs(
		&jobs.HelloWorldJob{},
	)
}
