// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden/pkg/resource"
	"medpoinraiden/internal/models"
)

func RegisterModels() {
	resource.RegisterModels(
		&models.Dokter{},
		&models.JadwalDokter{},
		&models.Kunjungan{},
		&models.Pasien{},
		&models.Pembayaran{},
		&models.Reservasi{},
		&models.Spesialisasi{},
	)
}
