// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden/pkg/resource"
	"medpoinraiden/internal/roles"
)

func RegisterRoles() {
	resource.RegisterRole(
		&roles.Admin{},
		&roles.Dokter{},
		&roles.User1{},
	)
}
