// Code generated by raiden-cli; DO NOT EDIT.
package Spesialisasi

import (
	"github.com/sev-2/raiden"
	"medpoinraiden/internal/models"
)

type RestController struct {
	raiden.ControllerBase
	Model models.Spesialisasi
}
